Easyfinder/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('backend.user.welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/token/{token}','Backend\VerificationController@verify')->name('user.verification');


Route::group(['prefix'=>'admin'],function(){
	//admin dashboard
	Route::get('/', 'Backend\AdminController@index')->name('admin.dashboard');

    //admin registration and verification
    Route::get('/register/submit','Auth\Admin\RegisterController@showRegistrationForm')->name('admin.register.submit');
	Route::post('/register','Auth\Admin\RegisterController@register')->name('admin.register');
	Route::get('/token/{token}', 'Backend\AdminVerificationController@verify')->name('admin.verification');
    //admin login and logout
	Route::get('/login','Auth\Admin\LoginController@showLoginForm')->name('admin.login');
	Route::post('/login/submit','Auth\Admin\LoginController@login')->name('admin.login.submit');
	Route::post('/logout','Auth\Admin\LoginController@logout')->name('admin.logout');
    //admin Forgotpassword and reset password
	Route::post('/password/email','Auth\Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	Route::get('/password/reset','Auth\Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	Route::get('/password/reset/{token}','Auth\Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');
	Route::post('/password/reset','Auth\Admin\ResetPasswordController@reset')->name('admin.password.reset.post');
	Route::resource('divisions','Backend\DivisionController');
	Route::resource('districts','Backend\DistrictController');
	Route::resource('upazilas','Backend\UpazilaController');
	Route::resource('unions','Backend\UnionController');
	Route::resource('cities','Backend\CityController');
	Route::resource('thanas','Backend\ThanaController');
	Route::resource('wards','Backend\WardController');
	Route::resource('comments','Backend\CommentController');
	Route::resource('bechelors','Backend\BechelorController');




	//for categories
	Route::group(['prefix'=>'categories'],function(){
	    Route::get('/',"Backend\CategoryController@index")->name('categories.index');
	    Route::get('/create',"Backend\CategoryController@create")->name('categories.create');
	    Route::post('/store',"Backend\CategoryController@store")->name('categories.store');
	    Route::get('/show/{id}',"Backend\CategoryController@show")->name('categories.show');
	    Route::get('/edit/{id}',"Backend\CategoryController@edit")->name('categories.edit');
	    Route::post('/update/{id}',"Backend\CategoryController@update")->name('categories.update');
	    Route::post('/delete/{id}',"Backend\CategoryController@delete")->name('categories.delete');

	});


	//order route details
	Route::group(['prefix'=>'orders'],function(){

		Route::get('/',"Backend\OrderController@index")->name('orders.index');
		Route::get('/create',"Backend\OrderController@create")->name('orders.create');
		Route::post('/store',"Backend\OrderController@store")->name('orders.store');
		Route::get('/show/{id}',"Backend\OrderController@show")->name('orders.show');
		Route::get('/edit/{id}',"Backend\OrderController@edit")->name('orders.edit');
		Route::post('/update/{id}',"Backend\OrderController@update")->name('orders.update');
		Route::post('/delete/{id}',"Backend\OrderController@destroy")->name('orders.destroy');

		//paid and Complete
		Route::post('/paid/{id}',"Backend\OrderController@orderPaid")->name('orders.paid');
		Route::post('/complete/{id}',"Backend\OrderController@orderComplete")->name('orders.complete');

	});
	Route::group(['prefix'=>'families'],function(){

		Route::get('/index', [
			'uses' => 'Backend\FamilyController@index',
			'as' => 'families.index'
		]);

		Route::get('/create', [
			'uses' => 'Backend\FamilyController@create',
			'as' => 'families.create'
		]);

		Route::post('/store', [
			'uses' => 'Backend\FamilyController@store',
			'as' => 'families-store'
		]);
		Route::get('/edit/{id}',[
			'uses'=>'Backend\FamilyController@edit',
			'as'=>'families-edit'
		]);

		Route::post('/update/{id}',[
			'uses'=>'Backend\FamilyController@update',
			'as'=>'families-update'
		]);

	});


	//card
	Route::group(['prefix'=>'cards'],function(){
		
		Route::get('/',"Backend\CardController@index")->name('cards.index');
		Route::get('/create',"Backend\CardController@create")->name('cards.create');
		Route::post('/store',"Backend\CardController@store")->name('cards.store');
		Route::get('/show/{id}',"Backend\CardController@show")->name('cards.show');
		Route::get('/edit/{id}',"Backend\CardController@edit")->name('cards.edit');
		Route::post('/update/{id}',"Backend\CardController@update")->name('cards.update');
		Route::post('/delete/{id}',"Backend\CardController@destroy")->name('cards.destroy');
	});

	Route::group(['prefix'=>'checkout'],function(){
		Route::get('/checkout',"Backend\CheckoutController@index")->name('checkout.index');
		Route::get('/checkout/create',"Backend\CheckoutController@create")->name('checkout.create');
		Route::post('/checkout',"Backend\CheckoutController@store")->name('checkout.store');
		Route::get('/checkout/show',"Backend\CheckoutController@show")->name('checkout.show');
		Route::get('/checkout/edit/{id}',"Backend\CheckoutController@edit")->name('checkout.edit');
		Route::post('/checkout/update/{id}',"Backend\CheckoutController@update")->name('checkout.update');
		Route::post('/checkout/delete/{id}',"Backend\CheckoutController@destroy")->name('checkout.destroy');
	});

});

//search for any thing
Route::get('/room-search','HomeController@room_search')->name('room-search');
//search city ,thana and ward
Route::get('/search', [
	'uses' => 'Backend\LocationController@search',
	'as' => 'search'
]);
// 
Route::post('/search_post/search_post', [
	'uses' => 'Backend\LocationController@search_post',
	'as' => 'search_post.search_post'
]);


//for divisions ,districts, upazilas and unions
Route::get('/divisions/ajax/{id}', [
	'uses' => 'Backend\LocationController@divisions_ajax',
	'as' => 'divisions'
]);

Route::get('/districts/ajax/{id}', [
	'uses' => 'Backend\LocationController@districts_ajax',
	'as' => 'districts'
]);

Route::get('/upazilas/ajax/{id}', [
	'uses' => 'Backend\LocationController@upazilas_ajax',
	'as' => 'upazilas'
]);


// for cities thanas and wards
Route::get('/cities/ajax/{id}', [
	'uses' => 'Backend\BechelorController@cities_ajax',
	'as' => 'cities'
]);

Route::get('/thanas/ajax/{id}', [
	'uses' => 'Backend\BechelorController@thanas_ajax',
	'as' => 'thanas'
]);

Easyfinder/app/Http/Controllers/Backend/ThanaController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Backend\Thana;
use App\Backend\City;

class ThanaController extends Controller
{

  public function __construct()
    {
        $this->middleware('auth:admin');
    }
      /**
       * Display a listing of the resource.
       *
       * @return \Illuminate\Http\Response
       */
      public function index()
      {
          $thanas =Thana::orderBy('id','desc')->get();
          return view('Backend.admin.thanas.index',compact('thanas'));
      }

      /**
       * Show the form for creating a new resource.
       *
       * @return \Illuminate\Http\Response
       */
      public function create()
      {
          $cities =City::orderBy('id','desc')->get();
          return view('Backend.admin.thanas.create',compact('cities'));
      }

      /**
       * Store a newly created resource in storage.
       *
       * @param  \Illuminate\Http\Request  $request
       * @return \Illuminate\Http\Response
       */
      public function store(Request $request)
      {
          $this->validate($request,[
            'name'=>'required|max:50|min:5',
          ]);

          $thanas=new Thana();
          $thanas->name=$request->name;
          $thanas->bangla_name=$request->bangla_name;
          $thanas->latitude=$request->latitude;
          $thanas->longitude=$request->longitude;
          $thanas->city_id=$request->city_id;
          //dd($thanas);
          $thanas->save();
          if(!is_null($thanas)){
            session()->flash('success','Thana create Successfully!!');
            return redirect()->route('thanas.index');
          }else{
            session()->flash('success','Some Error Occer!!');
            return back();
          }

      }

      /**
       * Display the specified resource.
       *
       * @param  int  $id
       * @return \Illuminate\Http\Response
       */
      public function show($id)
      {
           $thanas=Thana::findOrFail($id);
           //dd($thanas);
           return view('Backend.admin.thanas.show',compact('thanas'));
      }

      /**
       * Show the form for editing the specified resource.
       *
       * @param  int  $id
       * @return \Illuminate\Http\Response
       */
      public function edit($id)
      {
          $cities =City::orderBy('id','desc')->get();
          $thanas = Thana::findOrFail($id);
          return view('Backend.admin.thanas.edit',compact('cities','thanas'));
      }

      /**
       * Update the specified resource in storage.
       *
       * @param  \Illuminate\Http\Request  $request
       * @param  int  $id
       * @return \Illuminate\Http\Response
       */
      public function update(Request $request, $id)
      {
            //dd($id);
            $this->validate($request,[
              'name'=>'required|max:50|min:5',
              'city_id'=>'required',
            ]);

            $thanas=Thana::findOrFail($id);
            $thanas->name=$request->name;
            $thanas->bangla_name=$request->bangla_name;
            $thanas->latitude=$request->latitude;
            $thanas->longitude=$request->longitude;
            $thanas->city_id=$request->city_id;
            $thanas->update();
            if(!is_null($thanas)){
                session()->flash('success','Thana Update Successfully!!');
                return redirect()->route('thanas.index');
            }else{
                session()->flash('sticky_error','Some Error Occer!!');
                return back();
            }
      }

      /**
       * Remove the specified resource from storage.
       *
       * @param  int  $id
       * @return \Illuminate\Http\Response
       */
      public function destroy($id)
      {
          $thanas=Thana::find($id);
          if(!is_null($thanas))
          {
              $thanas->delete();
              session()->flash('success','Product has delete Successfully');
              return back();
          }else{
              session()->flash('sticky_error','Some Error Occer');
              return back();
          }

      }
}

Easyfinder/resources/views/backend/admin/thanas/create.blade.php
@extends('Backend.admin.layouts.master')
@section('content')
<div class="container">
  <div class="card card-register mx-auto mt-5">
    <div class="card-header">
      <h2>Thanas Create Form <span class="pull-right"><a href="{{ route('thanas.index')}}">Back</a></span></h2>
    </div>
    <div class="card-body">
      <form method="POST" action="{{ route('thanas.store') }}">
        @csrf
        <div class="form-group">
          <label for="latitude">City Name</label>
          <div class="form-input">
            <select name="city_id" class="form-control is-valid form-control-sm input-md" value="{{old('city_id')}}">
              <option value="0" disabled="true" selected="true">===Select Parent Category for this Category===</option>
              @foreach($cities as $city)
              <option value="{{$city->id}}">{{$city->name}}</option>
              @endforeach
            </select>
            <div class="valid-feedback">
              {{ ($errors->has('city_id')) ? $errors->first('city_id') : ''}}
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="name">Thana Name</label>
          <div class="form-input">
            <input type="text" class="form-control is-invalid form-control-sm" name="name" id="name" placeholder="Enter Thana name" value="" required>
            <div class="invalid-feedback">
              {{ ($errors->has('name')) ? $errors->first('name') : ''}}
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="bangla_name">Thana Bangla Name</label>
          <div class="form-input">
            <input type="text" class="form-control is-valid form-control-sm" name="bangla_name" id="bangla_name" placeholder="Enter Thana Bangla Name" value="">
            <div class="valid-feedback">
              {{ ($errors->has('bangla_name')) ? $errors->first('bangla_name') : ''}}
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="latitude">Thana Latitude</label>
          <div class="form-input">
            <input type="number" class="form-control is-valid form-control-sm input-md" step="0.01" name="latitude" id="latitude" placeholder="Enter Thana latitude" value="">
            <div class="valid-feedback">
              {{ ($errors->has('latitude')) ? $errors->first('latitude') : ''}}
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="longitude">Thana Longitude</label>
          <div class="form-input">
            <input type="number" class="form-control is-valid form-control-sm input-md"step="0.01" name="longitude" id="longitude" placeholder="Enter Thana longitude" value="">
            <div class="valid-feedback">
              {{ ($errors->has('longitude')) ? $errors->first('longitude') : ''}}
            </div>
          </div>
        </div>
        <button class="btn btn-primary" type="submit">Create</button>
      </form>
    </div>
  </div>
</div>
@endsection

Easyfinder/resources/views/backend/admin/thanas/edit.blade.php
@extends('Backend.admin.layouts.master')
@section('content')
<div class="container">
  <div class="card mx-auto mt-5">
    <div class="card-header">
      <h2>Thanas Create Form <span class="pull-right"><a href="{{ route('thanas.index')}}">Back</a></span></h2>
    </div>
    <div class="card-body">
      <form method="POST" action="{{ route('thanas.update',$thanas->id) }}" >
        @csrf
        @method('PUT')
        <div class="form-group">
          <label for="latitude">City Name</label>
          <div class="form-input">
            <select name="city_id" class="form-control is-valid form-control-sm input-md" value="{{old('city_id')}}">
              <option value="0" disabled="true" selected="true">===Select Under City===</option>
              @foreach($cities as $city)
              <option value="{{$city->id}}" {{ $city->id == $thanas->city_id ? 'selected' : ''}}>{{$city->name}}</option>
              @endforeach
            </select>
            <div class="valid-feedback">
              {{ ($errors->has('city_id')) ? $errors->first('city_id') : ''}}
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="name">Thana Name</label>
          <div class="form-input">
            <input type="text" class="form-control is-invalid form-control-sm" name="name" id="name" value="{{ $thanas->name}}">
            <div class="invalid-feedback">
              {{ ($errors->has('name')) ? $errors->first('name') : ''}}
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="bangla_name">Thana Bangla Name</label>
          <div class="form-input">
            <input type="text" class="form-control is-valid form-control-sm" name="bangla_name" id="bangla_name" value="{{ $thanas->bangla_name? $thanas->bangla_name:'N\A'}}">
            <div class="valid-feedback">
              {{ ($errors->has('bangla_name')) ? $errors->first('bangla_name') : ''}}
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="latitude">Thana Latitude</label>
          <div class="form-input">
            <input type="number" class="form-control is-valid form-control-sm input-md" step="0.01" name="latitude" id="latitude" value="{{ $thanas->latitude? $thanas->latitude:'0.00'}}">
            <div class="valid-feedback">
              {{ ($errors->has('latitude')) ? $errors->first('latitude') : ''}}
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="longitude">Thana Longitude</label>
          <div class="form-input">
            <input type="number" class="form-control is-valid form-control-sm input-md"step="0.01" name="longitude" id="longitude" value="{{ $thanas->longitude? $thanas->longitude:'0.00'}}">
            <div class="valid-feedback">
              {{ ($errors->has('longitude')) ? $errors->first('longitude') : ''}}
            </div>
          </div>
        </div>
        <button class="btn btn-primary" type="submit">Update</button>
      </form>
    </div>
  </div>
</div>
@endsection

Easyfinder/resources/views/backend/admin/thanas/index.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
  <div class="card mx-auto mt-5">
    <div class="card-header">
      <h2>Thanas Create Form <span class="pull-right"><a href="{{ route('thanas.create')}}">Back</a></span></h2>
    </div>
    <div class="card-body">Thana List<span class="pull-right"><a href="{{ route('thanas.create')}}">Create</a></span></h2>
      </div>
      <div class="table-responsive mt-2">
        <table id="thanas" class="table table-bordered table-striped">
          <caption>List of thanas</caption>
          <thead>
  					<tr>
  						<th>SL</th>
  						<th>Name</th>
  						<th>Bangla name</th>
  						<th>Latitude</th>
              <th>Longitude</th>
              <th>Parent Thana Name</th>
              <th>Show Details</th>
  						<th>Action</th>
  					</tr>
  				</thead>
  				<tbody>
  					<tr>
  						<div style="display: none;">{{$a=1}}</div>
  						@foreach($thanas as $thana)
  						<td>{{ $a++ }}</td>
  						<td>{{ $thana->name }}</td>
  						<td>
  						    @if($thana->bangla_name)
                  <p>{{ $thana->bangla_name}}</p>
                  @else
                    <p>N/A</p>
                  @endif
  						</td>
              <td>
  						    @if($thana->latitude)
                  <p>{{ $thana->latitude}}</p>
                  @else
                    <p>N/A</p>
                  @endif
  						</td>
              <td>
  						    @if($thana->longitude)
                  <p>{{ $thana->longitude}}</p>
                  @else
                    <p>N/A</p>
                  @endif
  						</td>
              <td style="color:green">{{$thana->city->name}}</td>
              <td>
                <a href="{{route('thanas.show', $thana->id)}}" class="badge badge-primary">Show</a>
              </td>
  						<td>
  							<a href="{{route('thanas.edit', $thana->id)}}" class="badge badge-warning">Edit</a>
                <a href="#" onclick="return confirm('are you sure')">
									<form class="pull-right form-inline" action="{{route('thanas.destroy', $thana->id)}}" method="POST">
										{{csrf_field()}}
										{{method_field('DELETE')}}
										<button class="badge badge-danger" type="submit">Delete</button>
									</form>
								</a>
  						</td>
  					</tr>
  					@endforeach
  				</tbody>
        </table>
      </div>
    </div>
  </div>
</div>
@endsection
@section('scripts')
<script>
	$(document).ready(function() {
    $('#thanas').DataTable();
} );
</script>
@endsection

Easyfinder/resources/views/backend/admin/thanas/show.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
  <div class="card mx-auto mt-5">
    <div class="card-header">
      <h2>Thanas Create Form <span class="pull-right"><a href="{{ route('thanas.index')}}">Back</a></span></h2>
    </div>
    <div class="card-body">
      <h4>Thana Details<a href="{{route('thanas.index')}}" class="btn btn-primary pull-right">Back</a></h4>
      <div class="row">
        <div class="col-sm-8">
          <div class="row">
            <div class="col-sm-6">
                   <p>Thana name</p>
                   <p>Thana Bangla Name</p>
                   <p>Thana Latitude </p>
                   <p>Longitude</p>
            </div>
            <div class="col-sm-6">
                   <p>City: {{$thanas->city->name}}, Thana: {{$thanas->name}}</p>
                   <p>{{$thanas->bangla_name?$thanas->bangla_name:'N\A'}} </p>
                   <p>{{$thanas->latitude?$thanas->latitude:'N\A'}} </p>
                   <p>{{$thanas->longitude?$thanas->longitude:'N\A'}} </p>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div id="map">

            </div>
        </div>

      </div>
    </div>
  </div>
</div>
@endsection