Easyfinder/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('backend.user.welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/token/{token}','Backend\VerificationController@verify')->name('user.verification');


Route::group(['prefix'=>'admin'],function(){
	//admin dashboard
	Route::get('/', 'Backend\AdminController@index')->name('admin.dashboard');

    //admin registration and verification
    Route::get('/register/submit','Auth\Admin\RegisterController@showRegistrationForm')->name('admin.register.submit');
	Route::post('/register','Auth\Admin\RegisterController@register')->name('admin.register');
	Route::get('/token/{token}', 'Backend\AdminVerificationController@verify')->name('admin.verification');
    //admin login and logout
	Route::get('/login','Auth\Admin\LoginController@showLoginForm')->name('admin.login');
	Route::post('/login/submit','Auth\Admin\LoginController@login')->name('admin.login.submit');
	Route::post('/logout','Auth\Admin\LoginController@logout')->name('admin.logout');
    //admin Forgotpassword and reset password
	Route::post('/password/email','Auth\Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	Route::get('/password/reset','Auth\Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	Route::get('/password/reset/{token}','Auth\Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');
	Route::post('/password/reset','Auth\Admin\ResetPasswordController@reset')->name('admin.password.reset.post');
	Route::resource('divisions','Backend\DivisionController');
	Route::resource('districts','Backend\DistrictController');
	Route::resource('upazilas','Backend\UpazilaController');
	Route::resource('unions','Backend\UnionController');
	Route::resource('cities','Backend\CityController');
	Route::resource('thanas','Backend\ThanaController');
	Route::resource('wards','Backend\WardController');
	Route::resource('comments','Backend\CommentController');
	Route::resource('bechelors','Backend\BechelorController');




	//for categories
	Route::group(['prefix'=>'categories'],function(){
	    Route::get('/',"Backend\CategoryController@index")->name('categories.index');
	    Route::get('/create',"Backend\CategoryController@create")->name('categories.create');
	    Route::post('/store',"Backend\CategoryController@store")->name('categories.store');
	    Route::get('/show/{id}',"Backend\CategoryController@show")->name('categories.show');
	    Route::get('/edit/{id}',"Backend\CategoryController@edit")->name('categories.edit');
	    Route::post('/update/{id}',"Backend\CategoryController@update")->name('categories.update');
	    Route::post('/delete/{id}',"Backend\CategoryController@delete")->name('categories.delete');

	});


	//order route details
	Route::group(['prefix'=>'orders'],function(){

		Route::get('/',"Backend\OrderController@index")->name('orders.index');
		Route::get('/create',"Backend\OrderController@create")->name('orders.create');
		Route::post('/store',"Backend\OrderController@store")->name('orders.store');
		Route::get('/show/{id}',"Backend\OrderController@show")->name('orders.show');
		Route::get('/edit/{id}',"Backend\OrderController@edit")->name('orders.edit');
		Route::post('/update/{id}',"Backend\OrderController@update")->name('orders.update');
		Route::post('/delete/{id}',"Backend\OrderController@destroy")->name('orders.destroy');

		//paid and Complete
		Route::post('/paid/{id}',"Backend\OrderController@orderPaid")->name('orders.paid');
		Route::post('/complete/{id}',"Backend\OrderController@orderComplete")->name('orders.complete');

	});
	Route::group(['prefix'=>'families'],function(){

		Route::get('/index', [
			'uses' => 'Backend\FamilyController@index',
			'as' => 'families.index'
		]);

		Route::get('/create', [
			'uses' => 'Backend\FamilyController@create',
			'as' => 'families.create'
		]);

		Route::post('/store', [
			'uses' => 'Backend\FamilyController@store',
			'as' => 'families-store'
		]);
		Route::get('/edit/{id}',[
			'uses'=>'Backend\FamilyController@edit',
			'as'=>'families-edit'
		]);

		Route::post('/update/{id}',[
			'uses'=>'Backend\FamilyController@update',
			'as'=>'families-update'
		]);

	});


	//card
	Route::group(['prefix'=>'cards'],function(){
		
		Route::get('/',"Backend\CardController@index")->name('cards.index');
		Route::get('/create',"Backend\CardController@create")->name('cards.create');
		Route::post('/store',"Backend\CardController@store")->name('cards.store');
		Route::get('/show/{id}',"Backend\CardController@show")->name('cards.show');
		Route::get('/edit/{id}',"Backend\CardController@edit")->name('cards.edit');
		Route::post('/update/{id}',"Backend\CardController@update")->name('cards.update');
		Route::post('/delete/{id}',"Backend\CardController@destroy")->name('cards.destroy');
	});

	Route::group(['prefix'=>'checkout'],function(){
		Route::get('/checkout',"Backend\CheckoutController@index")->name('checkout.index');
		Route::get('/checkout/create',"Backend\CheckoutController@create")->name('checkout.create');
		Route::post('/checkout',"Backend\CheckoutController@store")->name('checkout.store');
		Route::get('/checkout/show',"Backend\CheckoutController@show")->name('checkout.show');
		Route::get('/checkout/edit/{id}',"Backend\CheckoutController@edit")->name('checkout.edit');
		Route::post('/checkout/update/{id}',"Backend\CheckoutController@update")->name('checkout.update');
		Route::post('/checkout/delete/{id}',"Backend\CheckoutController@destroy")->name('checkout.destroy');
	});

});

//search for any thing
Route::get('/room-search','HomeController@room_search')->name('room-search');
//search city ,thana and ward
Route::get('/search', [
	'uses' => 'Backend\LocationController@search',
	'as' => 'search'
]);
// 
Route::post('/search_post/search_post', [
	'uses' => 'Backend\LocationController@search_post',
	'as' => 'search_post.search_post'
]);


//for divisions ,districts, upazilas and unions
Route::get('/divisions/ajax/{id}', [
	'uses' => 'Backend\LocationController@divisions_ajax',
	'as' => 'divisions'
]);

Route::get('/districts/ajax/{id}', [
	'uses' => 'Backend\LocationController@districts_ajax',
	'as' => 'districts'
]);

Route::get('/upazilas/ajax/{id}', [
	'uses' => 'Backend\LocationController@upazilas_ajax',
	'as' => 'upazilas'
]);


// for cities thanas and wards
Route::get('/cities/ajax/{id}', [
	'uses' => 'Backend\BechelorController@cities_ajax',
	'as' => 'cities'
]);

Route::get('/thanas/ajax/{id}', [
	'uses' => 'Backend\BechelorController@thanas_ajax',
	'as' => 'thanas'
]);

Easyfinder/app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Backend\Category;
use Image;
use File;

class CategoryController extends Controller
{
	    /**
	   * Display a listing of the resource.
	   *
	   * @return \Illuminate\Http\Response
	   */
	  public function index()
	  {
	      $categories =Category::orderBy('id','desc')->get();
	      return view('Backend.admin.categories.index',compact('categories'));
	  }

	  /**
	   * Show the form for creating a new resource.
	   *
	   * @return \Illuminate\Http\Response
	   */
	  public function create()
	  {
	      $categories = Category::orderBy('name','desc')->where('parent_id',NULL)->get();
	      return view('Backend.admin.categories.create',compact('categories'));
	  }

	  /**
	   * Store a newly created resource in storage.
	   *
	   * @param  \Illuminate\Http\Request  $request
	   * @return \Illuminate\Http\Response
	   */
	  public function store(Request $request)
	  {
	      $this->validate($request,[
	        'name'=>'required|max:50|min:5',
	      ]);

	      $categories=new Category();
	      $categories->name=$request->name;
	      $categories->parent_id=$request->parent_id;
	      $categories->description=$request->description;
	      if(count($request->image)>0)
	        {
	        	$image=$request->file('image');
	            $img=time().'.'.$image->getClientOriginalExtension();
	            $location=public_path('images/categories/'.$img);
	            Image::make($image)->save($location)->resize(300,300);
	            $categories->image=$img;
	        }
	      //dd($categories);
	      $categories->save();
	      if(!is_null($categories)){
	        session()->flash('success','Category create Successfully!!');
	        return redirect()->route('categories.index');
	      }else{
	        session()->flash('success','Some Error Occer!!');
	        return back();
	      }

	  }

	  /**
	   * Display the specified resource.
	   *
	   * @param  int  $id
	   * @return \Illuminate\Http\Response
	   */
	  public function show($id)
	  {
	       $categories=Category::findOrFail($id);
	       //dd($categories);
	       return view('Backend.admin.categories.show',compact('categories'));
	  }

	  /**
	   * Show the form for editing the specified resource.
	   *
	   * @param  int  $id
	   * @return \Illuminate\Http\Response
	   */
	  public function edit($id)
	  {
	     $main_categories = Category::orderBy('name','desc')->where('parent_id',NULL)->get();
	    $categories = Category::findOrFail($id);
	      if(!is_null($categories)){
	          return view('Backend.admin.categories.edit',compact('categories','main_categories'));
	      }else{
	          return redirect()->route('categories');
	      }
	  }

	  /**
	   * Update the specified resource in storage.
	   *
	   * @param  \Illuminate\Http\Request  $request
	   * @param  int  $id
	   * @return \Illuminate\Http\Response
	   */
	  public function update(Request $request, $id)
	  {
	        //dd($id);
	        $this->validate($request,[
	          'name'=>'required|max:50|min:5',
	          'parent_id'=>'required',
	        ]);

	        $categories=Category::findOrFail($id);
	        $categories->name=$request->name;
	        $categories->parent_id=$request->parent_id;
	        $categories->description=$request->description;
	        //dd($categories);
	        $categories->update();
	        if(!is_null($categories)){
	            session()->flash('success','Category Update Successfully!!');
	            return redirect()->route('categories.index');
	        }else{
	            session()->flash('sticky_error','Some Error Occer!!');
	            return back();
	        }
	  }

	  /**
	   * Remove the specified resource from storage.
	   *
	   * @param  int  $id
	   * @return \Illuminate\Http\Response
	   */
	  public function delete($id)
	  {
	      $categories=Category::find($id);
	      if(!is_null($categories))
	      {
	          $categories->delete();
	          session()->flash('success','Product has delete Successfully');
	          return back();
	      }else{
	          session()->flash('sticky_error','Some Error Occer');
	          return back();
	      }

	  }
}

Easyfinder/resources/views/backend/admin/categories/create.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
 		<div class="row ">
 			<div class="col-xs-8 col-sm-8 col-md-8 offset-xs-2 offset-sm-2 offset-md-2">
      <div class="card">
        <div class="card-header">
          <h2>Categories Create Form <span class="pull-right"><a href="{{ route('categories.index')}}">Back</a></span></h2>
        </div>
        <div class="card-body">
      <form method="POST" action="{{ route('categories.store') }}" enctype="multipart/form-data">
          @csrf

          <div class="form-group">
              <label for="name">Name</label>
              <div class="form-input">
                  <input type="text" class="form-control is-invalid form-control-sm" name="name" id="name" placeholder="Enter Category name" value="{{old('name')}}" required>
                  <div class="invalid-feedback">
                    {{ ($errors->has('name')) ? $errors->first('name') : ''}}
                  </div>
              </div>
          </div>

          <div class="form-group">
              <label for="parent_id">Select Parent Category</label>
              <div class="form-input">
                  <select name="parent_id" id="parent_id" class="form-control is-valid form-control-sm input-md" value="">
                          <option value="0" disabled="true" selected="true">===Select Parent Category for this Category===</option>
                          @foreach($categories as $category)
                          <option value="{{$category->id}}">{{$category->name}}</option>
                          @endforeach
                  </select>
                  <div class="valid-feedback">
                    {{ ($errors->has('parent_id')) ? $errors->first('parent_id') : ''}}
                  </div>
              </div>
          </div>

          <div class="form-group">
              <label for="description">Description</label>
              <div class="form-input">
                  <textarea name="description" cols="4" rows="5" value="{{old('description')}}" class="form-control is-valid form-control-sm input-md" id="description"required>{{ old('description')}}</textarea>
                  <div class="valid-feedback">
                    {{ ($errors->has('description')) ? $errors->first('description') : ''}}
                  </div>
              </div>
          </div>


          <div class="form-group">
              <label for="image">Category Image</label>
              <div class="form-input">
                  <input type="file" class="form-control is-valid form-control-sm" name="image" id="image" placeholder="Enter Ward Bangla Name" value="">
                  <div class="valid-feedback">
                    {{ ($errors->has('image')) ? $errors->first('image') : ''}}
                  </div>
              </div>
          </div>


          <button class="btn btn-primary" type="submit">Create</button>
      </form>
    </div>
  </div>
</div>

</div>
</div>
@endsection

Easyfinder/resources/views/backend/admin/categories/edit.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xl-12 col-lg-12">
      <div class="row">
        <div class="col-sm-8">
          <div class="card">
                <div class="card-header">
                  <h2>Category Edit <span class="pull-right"><a href="{{ route('categories.index')}}">Back</a></span></h2>
                </div>
                 <div class="card-body">
                   <form method="post" action="{{ route('categories.update',$categories->id) }}" enctype="multipart/form-data" >
                       @csrf
                       <div class="form-group">
                           <label for="name">Category Name</label>
                           <div class="form-input">
                               <input type="text" class="form-control is-invalid form-control-sm" name="name" id="name" value="{{ $categories->name}}">
                               <div class="invalid-feedback">
                                 {{ ($errors->has('name')) ? $errors->first('name') : ''}}
                               </div>
                           </div>
                       </div>

                       <div class="form-group">
                           <label for="parent_id">Primary Name Off Category</label>
                           <div class="form-input">
                               <select name="parent_id" id="parent_id" class="form-control is-valid form-control-sm input-md">
                                       <option value="0" disabled="true" selected="true">===Select Parent Category===</option>
                                       @foreach($main_categories as $category)
                                       <option value="{{$category->id}}" {{ $category->id == $categories->parent_id ? 'selected' : ''}}>{{$category->name}}</option>
                                       @endforeach
                               </select>
                               <div class="valid-feedback">
                                 {{ ($errors->has('parent_id')) ? $errors->first('parent_id') : ''}}
                               </div>
                           </div>
                       </div>


                        <div class="form-group">
                            <label for="description">Description</label>
                            <div class="form-input">
                                <textarea name="description" cols="4" rows="5" class="form-control is-valid form-control-sm input-md" id="description">{{ $categories->description }}</textarea>
                                <div class="valid-feedback">
                                  {{ ($errors->has('description')) ? $errors->first('description') : ''}}
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="image">Category Image</label>
                            <div class="form-input">
                                <input type="file" class="form-control is-valid form-control-sm input-md" name="image" id="image" value="{{ old('image')}}">
                                <div class="valid-feedback">
                                  {{ ($errors->has('image')) ? $errors->first('image') : ''}}
                                </div>
                            </div>
                        </div>

                        <button class="btn btn-primary" type="submit">Update</button>
                    </form>
                  </div>
                </div>
              </div>
        <div class="col-sm-4">
          <div id="map">

  </div>
        </div>

      </div>
    </div>
  </div>
</div>
@endsection

Easyfinder/resources/views/backend/admin/categories/index.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
  <div class="row align-items-center">
    <div class="col-md-12 col-sm-12 col-xl-12 col-lg-12">
      <div class="card-header mt-2">
        <h2>Category List<span class="pull-right"><a href="{{ route('categories.create')}}">Create</a></span></h2>
      </div>
      <div class="table-responsive mt-2">
        <table id="categories" class="table table-bordered table-striped">
          <caption>List of categories</caption>
          <thead>
  					<tr>
  						<th>SL</th>
  						<th>Name</th>
  						<th>Description</th>
  						<th>Image</th>
              <th>Parent Of the Category</th>
              <th>Show</th>
  						<th>Action</th>
  					</tr>
  				</thead>
  				<tbody>
  					<tr>
  						<div style="display: none;">{{$a=1}}</div>
  						@foreach($categories as $category)
  						<td>{{ $a++ }}</td>
  						<td>{{ $category->name }}</td>
  						<td>
  						    @if($category->description)
                  <p>{{ $category->description}}</p>
                  @else
                    <p>N/A</p>
                  @endif
  						</td>
              <td>
  						    @if($category->image)
                  <p>{{ $category->image}}</p>
                  @else
                    <p>N/A</p>
                  @endif
  						</td>
              <td style="color: red">
							@if($category->parent_id==null)
							Primary Category
							@else
							{{ $category->parent->name }}
							@endif
						</td>
              <td>
                <a href="{{route('categories.show', $category->id)}}" class="badge badge-primary">Show</a>
              </td>
  						<td>
  							<a href="{{route('categories.edit', $category->id)}}" class="badge badge-warning">Edit</a>
                <a href="#DeleteModal{{ $category->id}}" data-toggle="modal" class="badge badge-danger btn-sm">Delete</a>
								<div class="modal fade" id="DeleteModal{{$category->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
									<div class="modal-dialog" role="document">
										<div class="modal-content">
											<div class="modal-header">
												<h5 class="modal-title" id="exampleModalLabel">Are You Sure To Delete!</h5>
												<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span>
												</button>
											</div>
											<div class="modal-body">
												<form action="{{ route('categories.delete', $category->id)}}" method="POST">
													{{csrf_field()}}
												<button type="submit" class="badge badge-success">Delete</button>
												</form>
											</div>
											<div class="modal-footer">
												<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
											</div>
										</div>
									</div>
								</div>
							</a>
  						</td>
  					</tr>
  					@endforeach
  				</tbody>
        </table>
      </div>
    </div>
  </div>
</div>
@endsection
@section('scripts')
<script>
	$(document).ready(function() {
    $('#categories').DataTable();
} );
</script>
@endsection

Easyfinder/resources/views/backend/admin/categories/show.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="container">
  <div class="row align-items-center">
    <div class="col-md-12 col-sm-12 col-xl-12 col-lg-12">
      <h4>District Details<a href="{{route('districts.index')}}" class="btn btn-primary pull-right">Back</a></h4>
      <div class="row">
        <div class="col-sm-8">
          <div class="row">
            <div class="col-sm-4">
                   <p>Thana name</p>
                   <p>Thana Bangla Name</p>
                   <p>Thana Latitude </p>
                   <p>Longitude</p>
            </div>
            <div class="col-sm-8">
                   <p>Division: {{$districts->division->name}}, District: {{$districts->name}}</p>
                   <p>{{$districts->bangla_name?$districts->bangla_name:'N\A'}} </p>
                   <p>{{$districts->latitude?$districts->latitude:'N\A'}} </p>
                   <p>{{$districts->longitude?$districts->longitude:'N\A'}} </p>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div id="map">

  </div>
        </div>

      </div>
    </div>
  </div>
</div>
@endsection