Easyfinder/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('backend.user.welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/token/{token}','Backend\VerificationController@verify')->name('user.verification');


Route::group(['prefix'=>'admin'],function(){
	//admin dashboard
	Route::get('/', 'Backend\AdminController@index')->name('admin.dashboard');

    //admin registration and verification
    Route::get('/register/submit','Auth\Admin\RegisterController@showRegistrationForm')->name('admin.register.submit');
	Route::post('/register','Auth\Admin\RegisterController@register')->name('admin.register');
	Route::get('/token/{token}', 'Backend\AdminVerificationController@verify')->name('admin.verification');
    //admin login and logout
	Route::get('/login','Auth\Admin\LoginController@showLoginForm')->name('admin.login');
	Route::post('/login/submit','Auth\Admin\LoginController@login')->name('admin.login.submit');
	Route::post('/logout','Auth\Admin\LoginController@logout')->name('admin.logout');
    //admin Forgotpassword and reset password
	Route::post('/password/email','Auth\Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	Route::get('/password/reset','Auth\Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	Route::get('/password/reset/{token}','Auth\Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');
	Route::post('/password/reset','Auth\Admin\ResetPasswordController@reset')->name('admin.password.reset.post');
	Route::resource('divisions','Backend\DivisionController');
	Route::resource('districts','Backend\DistrictController');
	Route::resource('upazilas','Backend\UpazilaController');
	Route::resource('unions','Backend\UnionController');
	Route::resource('cities','Backend\CityController');
	Route::resource('thanas','Backend\ThanaController');
	Route::resource('wards','Backend\WardController');
	Route::resource('comments','Backend\CommentController');
	Route::resource('bechelors','Backend\BechelorController');




	//for categories
	Route::group(['prefix'=>'categories'],function(){
	    Route::get('/',"Backend\CategoryController@index")->name('categories.index');
	    Route::get('/create',"Backend\CategoryController@create")->name('categories.create');
	    Route::post('/store',"Backend\CategoryController@store")->name('categories.store');
	    Route::get('/show/{id}',"Backend\CategoryController@show")->name('categories.show');
	    Route::get('/edit/{id}',"Backend\CategoryController@edit")->name('categories.edit');
	    Route::post('/update/{id}',"Backend\CategoryController@update")->name('categories.update');
	    Route::post('/delete/{id}',"Backend\CategoryController@delete")->name('categories.delete');

	});


	//order route details
	Route::group(['prefix'=>'orders'],function(){

		Route::get('/',"Backend\OrderController@index")->name('orders.index');
		Route::get('/create',"Backend\OrderController@create")->name('orders.create');
		Route::post('/store',"Backend\OrderController@store")->name('orders.store');
		Route::get('/show/{id}',"Backend\OrderController@show")->name('orders.show');
		Route::get('/edit/{id}',"Backend\OrderController@edit")->name('orders.edit');
		Route::post('/update/{id}',"Backend\OrderController@update")->name('orders.update');
		Route::post('/delete/{id}',"Backend\OrderController@destroy")->name('orders.destroy');

		//paid and Complete
		Route::post('/paid/{id}',"Backend\OrderController@orderPaid")->name('orders.paid');
		Route::post('/complete/{id}',"Backend\OrderController@orderComplete")->name('orders.complete');

	});
	Route::group(['prefix'=>'families'],function(){

		Route::get('/index', [
			'uses' => 'Backend\FamilyController@index',
			'as' => 'families.index'
		]);

		Route::get('/create', [
			'uses' => 'Backend\FamilyController@create',
			'as' => 'families.create'
		]);

		Route::post('/store', [
			'uses' => 'Backend\FamilyController@store',
			'as' => 'families-store'
		]);
		Route::get('/edit/{id}',[
			'uses'=>'Backend\FamilyController@edit',
			'as'=>'families-edit'
		]);

		Route::post('/update/{id}',[
			'uses'=>'Backend\FamilyController@update',
			'as'=>'families-update'
		]);

	});


	//card
	Route::group(['prefix'=>'cards'],function(){
		
		Route::get('/',"Backend\CardController@index")->name('cards.index');
		Route::get('/create',"Backend\CardController@create")->name('cards.create');
		Route::post('/store',"Backend\CardController@store")->name('cards.store');
		Route::get('/show/{id}',"Backend\CardController@show")->name('cards.show');
		Route::get('/edit/{id}',"Backend\CardController@edit")->name('cards.edit');
		Route::post('/update/{id}',"Backend\CardController@update")->name('cards.update');
		Route::post('/delete/{id}',"Backend\CardController@destroy")->name('cards.destroy');
	});

	Route::group(['prefix'=>'checkout'],function(){
		Route::get('/checkout',"Backend\CheckoutController@index")->name('checkout.index');
		Route::get('/checkout/create',"Backend\CheckoutController@create")->name('checkout.create');
		Route::post('/checkout',"Backend\CheckoutController@store")->name('checkout.store');
		Route::get('/checkout/show',"Backend\CheckoutController@show")->name('checkout.show');
		Route::get('/checkout/edit/{id}',"Backend\CheckoutController@edit")->name('checkout.edit');
		Route::post('/checkout/update/{id}',"Backend\CheckoutController@update")->name('checkout.update');
		Route::post('/checkout/delete/{id}',"Backend\CheckoutController@destroy")->name('checkout.destroy');
	});

});

//search for any thing
Route::get('/room-search','HomeController@room_search')->name('room-search');
//search city ,thana and ward
Route::get('/search', [
	'uses' => 'Backend\LocationController@search',
	'as' => 'search'
]);
// 
Route::post('/search_post/search_post', [
	'uses' => 'Backend\LocationController@search_post',
	'as' => 'search_post.search_post'
]);


//for divisions ,districts, upazilas and unions
Route::get('/divisions/ajax/{id}', [
	'uses' => 'Backend\LocationController@divisions_ajax',
	'as' => 'divisions'
]);

Route::get('/districts/ajax/{id}', [
	'uses' => 'Backend\LocationController@districts_ajax',
	'as' => 'districts'
]);

Route::get('/upazilas/ajax/{id}', [
	'uses' => 'Backend\LocationController@upazilas_ajax',
	'as' => 'upazilas'
]);


// for cities thanas and wards
Route::get('/cities/ajax/{id}', [
	'uses' => 'Backend\BechelorController@cities_ajax',
	'as' => 'cities'
]);

Route::get('/thanas/ajax/{id}', [
	'uses' => 'Backend\BechelorController@thanas_ajax',
	'as' => 'thanas'
]);

Easyfinder/app/Http/Controllers/Backend/CardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Backend\Card;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Auth;
use File;

class CardController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.admin.cards.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request);
        $this->validate($request,[
            'seat'=>'required',
        ]);

        $cards=new Card();
        if(Auth::check()){
            $cards->user_id=Auth::id();
        }
        $cards->seat=$request->seat;
        $cards->bechelor_id=$request->bechelor_id;
        $cards->ip_address=$request->ip();
        //dd($cards);
        $cards->save();
        return redirect()->route('cards.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $cards=Card::findOrFail($id);
        //dd($cards);
        if(!is_null($cards)){
            $cards->seat=$request->seat;
            $cards->update();
            return redirect()->route('cards.index');
        }else{
            return redirect('cards');
        }
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cards=Card::findOrFail($id);
        //dd($cards);
        if(!is_null($cards))
        {
            $cards->delete();
            
        }else{
            return redirect('cards');
        }
        session()->flash('success','Product has delete Successfully');
        return back();
    }
}

Easyfinder/resources/views/backend/admin/Cards/card-button.blade.php
<div class="card-header" mt-2 style="background-color: pink">
<form class="form-inline" action="{{ route('cards.store', $bechelor->id)}}" method="POST">
	{{csrf_field()}}

	<input type="hidden" name="bechelor_id" value="{{$bechelor->id}}">

	<div class="form-group">
          <label for="seat" style="margin-left: 20px">How Many Seat Do You Booking?</label>
          <div class="form-input" style="margin-left: 20px">
            <input type="number" class="form-control is-valid form-control-sm input-md" name="seat" id="seat" placeholder="" value="">
            <div class="valid-feedback">
              {{ ($errors->has('seat')) ? $errors->first('seat') : ''}}
            </div>
          </div>
        </div>
        <hr>
	<button type="submit" class="badge badge-pill badge-primary"><i class="fa fa-plus">Card To Booking</i></button>
</form>
</div>

Easyfinder/resources/views/backend/admin/Cards/index.blade.php
@extends('Backend.admin.layouts.master')
@section('content')
<div class="container">
	<div class="card mx-auto mt-5">
		<div class="card">
			<div class="card-header">
				<p class="small text-center text-muted mt-2">
					<img src="{{asset('images/bechelor_room/bechelor_room.jpg')}}" height="80px" width="100%">
				</p>
			</div>
			<div class="card-body">
				@if(App\Backend\Card::total_Cards()->count() > 0)
				<table id="schedule" class="table table-bordered">
					<thead>
						<tr>
							<th rowspan="2">SL</th>
							<th rowspan="2">Title</th>
							<th rowspan="2">Image</th>
							<th rowspan="2">Seat</th>
							<th rowspan="2">Price</th>
							<th rowspan="2">Total Price</th>
							<th rowspan="2">Action</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							@php
							$total_price=0;
							@endphp
							<div style="display: none;">{{$a=1}}</div>
							@foreach(App\Backend\Card::total_Cards() as $card)
							<td>{{ $a++ }}</td>
							<td>
								<a href="{{route('bechelors.show',$card->bechelor->title)}}">{{ $card->bechelor->title}}</a>
							</td>
							<td>
								<div id="demo" class="carousel slide" data-ride="carousel">
									<!-- The slideshow -->
									<div class="carousel-inner">
										<div class="carousel-inner">
											@php
											$i=1
											@endphp
											@foreach($card->bechelor->images as $image)
											<div style="text-align: center;" class="carousel-item {{$i==1 ? 'active' : ''}}">
												<img class="img-fluid img-thumbnail" src="{{asset('images/bechelor_room/'.$image->images)}}" alt="" >
											</div>
											@php
											$i++
											@endphp
											@endforeach
										</div>
										
									</div>
									<!-- Left and right controls -->
									<a class="carousel-control-prev" href="#demo" data-slide="prev">
										<span class="carousel-control-prev-icon"></span>
									</a>
									<a class="carousel-control-next" href="#demo" data-slide="next">
										<span class="carousel-control-next-icon"></span>
									</a>
								</div>
							</td>
							<td>
								<form style="margin-left: 40px" class="form-inline" action="{{ route('cards.update', $card->id)}}" method="POST">
									{{csrf_field()}}
									<input type="number" value="{{$card->seat}}" name="seat" class="col-sm-6 form-control">
									<button type="submit" class="btn btn-outline-primary btn-sm">Update</button>
								</form>
							</td>
							<td>{{$card->bechelor->room_rent}} Taka</td>
							<td>{{$card->bechelor->room_rent * $card->seat}} Taka</td>
							<td>
								<a href="#DeleteModal{{ $card->id}}" data-toggle="modal" class="btn btn-outline-danger btn-sm">Delete</a>
								<div class="modal fade" id="DeleteModal{{$card->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
									<div class="modal-dialog" role="document">
										<div class="modal-content">
											<div class="modal-header">
												<h5 class="modal-title" id="exampleModalLabel">Are You Sure To Delete!</h5>
												<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span>
												</button>
											</div>
											<div class="modal-body">
												<form action="{{ route('cards.destroy', $card->id)}}" method="POST">
													{{csrf_field()}}
													<button type="submit" class="btn btn-outline-primary btn-lg">Delete</button>
												</form>
											</div>
											<div class="modal-footer">
												<button type="button" class="btn btn-outline-success btn-lg" data-dismiss="modal">Close</button>
											</div>
										</div>
									</div>
								</div>
							</td>
						</tr>
						@php
						$total_price+=$card->bechelor->room_rent * $card->seat
						@endphp
						@endforeach
						<tr>
							<th style="margin-left: 120px" colspan="5">Total Amount</th>
							<th colspan="2">{{ $total_price }} Taka</th>
						</tr>
					</tbody>
				</table>
				<div class="float-right">
					<a href="{{ route('bechelors.index')}}" class="btn btn-outline-info btn-lg">Bechelor Room</a>
					<a href="{{ route('checkout.index')}}" class="btn btn-outline-warning btn-lg">Payment</a>
					
				</div>
				@else
				<p class="badge badge-success" style="text-align: center; font-size: 20px">
					No Iteam in your Card
				</p>
				<br>
				<a href="{{ route('bechelors.index')}}" class="btn btn-outline-info btn-lg margin-top-20">Continue Shopping</a>
				@endif
			</div>
		</div>
	</div>
</div>
@endsection